import { properties } from "./types";
export const Properties: properties[] = [
  {
    id: "2b8c4df1-9c2a-4f7b-8f1b-1f78d5e3c8d7",
    title: "Modern Family Home",
    description: "A spacious and modern home perfect for a growing family.",
    price: 400000,
    address: {
      street: "123 Pine St",
      city: "Dallas",
      state: "TX",
      country: "USA",
    },
    type: "house",
    bedroom: "4-6",
    amenities: ["Swimming Pool", "Garden", "Garage"],
    images: ["image1.jpg", "image2.jpg"],
    area: "2500 sqft",
  },
  {
    id: "3b8f7c2a-6a1c-4f3d-8c9e-4f8b9c3e7d1a",
    title: "Cozy Urban Apartment",
    description: "A comfortable apartment in the heart of the city.",
    price: 275000,
    address: {
      street: "789 Elm St",
      city: "San Francisco",
      state: "CA",
      country: "USA",
    },
    type: "house",
    bedroom: "2-4",
    amenities: ["Balcony", "Gym", "Pet Friendly"],
    images: ["image3.jpg", "image4.jpg"],
    area: "900 sqft",
  },
  {
    id: "8fdc3b56-7690-46e2-a49f-13fdfcd287f4",
    title: "Urban Loft",
    description: "A chic loft in the city center, close to all amenities.",
    price: 350000,
    address: {
      street: "456 Central Ave",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
    },
    type: "house",
    bedroom: "2-4",
    amenities: ["Elevator", "Gym", "24/7 Security"],
    images: ["image5.jpg", "image6.jpg"],
    area: "1200 sqft",
  },
  {
    id: "fb34d64a-6c78-44e5-9db9-85b2fd0f4a1f",
    title: "Luxury Penthouse",
    description: "A stunning penthouse with panoramic views of the ocean.",
    price: 900000,
    address: {
      street: "789 Ocean Blvd",
      city: "Miami",
      state: "FL",
      country: "USA",
    },
    type: "house",
    bedroom: "4-6",
    amenities: ["Private Pool", "Roof Terrace", "Concierge Service"],
    images: ["image7.jpg", "image8.jpg"],
    area: "3000 sqft",
  },
  {
    id: "eabc1321-3bf7-492d-8b37-f7cd78bff6cd",
    title: "Downtown Office Space",
    description: "Prime office space located in the heart of downtown.",
    price: 450000,
    address: {
      street: "123 Business St",
      city: "Chicago",
      state: "IL",
      country: "USA",
    },
    type: "commercial",
    bedroom: "2-4",
    amenities: ["Conference Rooms", "High-Speed Internet", "Parking"],
    images: ["image9.jpg", "image10.jpg"],
    area: "1500 sqft",
  },
  {
    id: "d12abf09-2398-456f-89f2-3e3449d8c2db",
    title: "Cozy Suburban Home",
    description: "A charming home in a quiet suburban neighborhood.",
    price: 275000,
    address: {
      street: "456 Maple St",
      city: "Austin",
      state: "TX",
      country: "USA",
    },
    type: "house",
    bedroom: "4-6",
    amenities: ["Backyard", "Garage", "Nearby Park"],
    images: ["image11.jpg", "image12.jpg"],
    area: "2000 sqft",
  },
  {
    id: "b13de4c8-67f2-4bca-9389-0c7e7f61b4b8",
    title: "Mountain Retreat",
    description: "A serene retreat in the mountains, ideal for nature lovers.",
    price: 600000,
    address: {
      street: "789 Mountain Rd",
      city: "Aspen",
      state: "CO",
      country: "USA",
    },
    type: "house",
    bedroom: "4-6",
    amenities: ["Fireplace", "Hiking Trails", "Hot Tub"],
    images: ["image13.jpg", "image14.jpg"],
    area: "2800 sqft",
  },
  {
    id: "9d7a6bfe-cd6f-4bb5-8d8b-6b4f6e9e2b3c",
    title: "Beachfront Condo",
    description: "A luxurious condo with direct access to the beach.",
    price: 750000,
    address: {
      street: "321 Ocean View Dr",
      city: "Santa Monica",
      state: "CA",
      country: "USA",
    },
    type: "house",
    bedroom: "4-6",
    amenities: ["Beach Access", "Fitness Center", "Security"],
    images: ["image15.jpg", "image16.jpg"],
    area: "2200 sqft",
  },
  {
    id: "a2c4e8b9-7d1a-4d2f-8e2a-1c3f9b4e6d8f",
    title: "Lakefront Cabin",
    description: "A cozy cabin with stunning lake views and modern amenities.",
    price: 500000,
    address: {
      street: "456 Lake Rd",
      city: "Lake Tahoe",
      state: "NV",
      country: "USA",
    },
    type: "house",
    bedroom: "2-4",
    amenities: ["Lake Access", "Fire Pit", "Dock"],
    images: ["image17.jpg", "image18.jpg"],
    area: "1800 sqft",
  },
  {
    id: "6c2b7f4e-3a8f-4c8b-9e4c-1f7b3d2e8f6a",
    title: "Country Estate",
    description:
      "A grand estate in the countryside, perfect for large families.",
    price: 1200000,
    address: {
      street: "123 Country Ln",
      city: "Nashville",
      state: "TN",
      country: "USA",
    },
    type: "house",
    bedroom: "6-8",
    amenities: ["Barn", "Orchard", "Guest House"],
    images: ["image19.jpg", "image20.jpg"],
    area: "5000 sqft",
  },
];
