import type { Metadata } from "next";
import { ABeeZee } from "next/font/google";
import "./globals.css";
import {
  CurrentUserContextProvider,
  SearchCriteraContextProvider,
} from "./components/context";

const inter = ABeeZee({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CurrentUserContextProvider>
          <SearchCriteraContextProvider>
            {children}
          </SearchCriteraContextProvider>
        </CurrentUserContextProvider>
      </body>
    </html>
  );
}
